version: "3"

services:
  red:
    build: .
    container_name: node-red
    ports:
      - 1880:1880
    volumes:
      - ./data:/data
    #   - ./public:/home/nol/node-red-static
    links:
      # - mongodb
      - mqtt
  mqtt:
    image: eclipse-mosquitto:1.6.12
    container_name: mqtt-broker
    ports:
      - 1883:1883
  # mongodb:
  #   ports:
  #     - 27017:27017
  #   image: arm64v8/mongo:4
  #   container_name: mongodb
  #   volumes:
  #     - ./db:/data/db
  #   restart: unless-stopped

networks:
  app-networks:
    external:
      name: nodered_default